spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test
#    username: sa
#    password:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: create
#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.type: trace
